backend:
  name: github
  repo: anon0v0/mygo-blog
  branch: main
  base_url: https://oauth.saki.li
  auth_endpoint: /auth

locale: 'zh_Hans'

media_folder: "src/assets/images"
public_folder: "../../assets/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "published", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "封面图", name: "image", widget: "image", required: false }
      - { label: "标签", name: "tags", widget: "list", default: [] }
      - { label: "分类", name: "category", widget: "string" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "语言", name: "lang", widget: "string", required: false, default: "" }
      - { label: "正文", name: "body", widget: "markdown" }
